### ISSUE TITLE
Very Critical Spelling Error HIGH PRIORITY

### ISSUE THREAD

**Issue by saedang** [Metruzero/Minesweeper#1]
You spelled receive wrong. Fix it.

**Comment by Metruzero** [comment]
Can you give me the line number and file?

**Comment by saedang** [comment]
GridController.cs like 195. Fix it now.

**Comment by Metruzero** [comment]
No

**Comment by saedang** [comment]
Okay, let's do this the hard way.

**Comment by Metruzero** [comment]
Fine I fixed it
